### ISSUE TITLE
Python dependency

### ISSUE THREAD

**Issue by 3v** [sous-chefs/graphite#254]
Python cookbook is deprecated and is suggesting to use poise-python instead.

**Comment by luckymike** [comment]
This will remove Chef 11 support, which is fine, but needs to be a major bump which arguably requires a little planning. Then again, it's not like other features have been flowing to the current major version :)

**Comment by yticketfly** [comment]
Is there a workaround this?
` Error executing action `install` on resource 'python_pip[uwsgi]'`

**Comment by tas50** [comment]
it's time to do the bump at this point. Chef 12 has been out for 18 months and we've removed support for Chef 11 from all chef managed community cookbooks. This cookbook already depends on cookbooks that require Chef 12.

**Comment by howdoicomputer** [comment]
This would also make it easier to use PyPy. I saw a branch for migrating over to poise-python done by @luckymike  but it looked abandoned. Would contributions be welcome? I could do the migration work.

**Comment by luckymike** [comment]
No really abandoned, just held on the question of ditching Chef 11, which I think is resolved.

**Comment by webframp** [comment]
agreed! I think we can assume Chef 12 only at this point.

**Comment by howdoicomputer** [comment]
Sweet! Thanks for chiming in. Good to hear that goodness is coming.

**Comment by tas50** [comment]
I'm currently working on a getting a working graphite cookbook out the door. Graphite expects Python 2.7 now, which bumps the Django dep and changes a lot of config steps.  This is currently going on in #266. After that I plan on cutting a Chef 12.1+ release using some of the new custom resource accumulator logic we've developed at Chef. This new release will also remove the use of Runit, and instead use Upstart/Systemd depending on the distro release. That makes it easier to test since Runit fails in kitchen-dokken and also allows for openSUSE support where there aren't runit packages.

**Comment by howdoicomputer** [comment]
@tas50 That sounds fantastic!

Does runit really not work in dokken? I just setup a wrapper cookbook and converges at least complete.

```
  User root
     ✔  should exist
     ○  This is an example test, replace with your own test.
  Port 80
     ✔  should not be listening
     ○  This is an example test, replace with your own test.

Test Summary: 2 successful, 0 failures, 2 skipped
       Finished verifying <default-ubuntu-1604> (0m0.68s).
-----> Destroying <default-ubuntu-1604>...
       Finished destroying <default-ubuntu-1604> (0m1.32s).
       Finished testing <default-ubuntu-1604> (3m53.32s).
-----> Kitchen is finished. (3m53.96s)
```

**Comment by tas50** [comment]
Randomly blows up for me in Travis.

**Comment by webframp** [comment]
Seems like it would just be a matter of getting the right pid_one_command?
ref: https://github.com/someara/kitchen-dokken#process-orientation

I don't mind removing the default of runit, but removing completely seems like a bit of a departure from current functionality?

**Comment by luckymike** [comment]
:+1: to @webframp's comments. Also, adjusting a cookbook's behavior to facilitate an arbitrary test platform seems like a major anti-pattern.

**Comment by tas50** [comment]
The goal is definetly not to adjust the behavior for the tests. There's ways to tweak the testing to make things work. Here's a few reasons we've systematically removed Runit from cookbooks that Chef manages.

1) Runit as a project is basically dead. I'm fairly certain this has a lot to do with #2
2) Runit was used extensively in Chef since at the time we only had sys-v and that didn't provide reliability. We needed something that could start services back up when they failed and had easy to write definitions. Modern init systems (upstart/systemd) provide the reliability we need and their definitions are dead simple to write. We even have built in support in Chef for systemd_unit files which makes things even better.
3) Runit is confusing to those not familiar with it or expecting a runit service. Logs in /etc/ is really weird to people and in general a user probably doesn't want/expect runit to be running services setup by cookbooks. Native init systems provide the experience people most likely want / expect.
4) Runit is not available on every platform so we limit our platform support by using runit. The installation on RHEL is questionable at best since it's not an official package and there are no suse packages.

**Comment by tas50** [comment]
Here's an example of a cookbook that previously defaulted to runit. We migrated service management over to a custom resource and retained runit support, but removed it as the default. If you REALLY wanted it you could keep it, but otherwise you'd get a new service running on a native init system.

https://github.com/chef-cookbooks/push-jobs/tree/master/resources

**Comment by luckymike** [comment]
I think those are good points @tas50, and I'd welcome a runit 🔪 in v3.0. I think v2.x should focus on updating the python dependencies, dropping Chef 11 support, and adding in the new init options, as those are either enhancements or fixes for existing users. 

As I've apparently been kicked out of this cookbook org, I guess these are user rather than maintainer suggestions. 😛

**Comment by webframp** [comment]
@tas50 sounds reasonable to me, as long as runit is available as an option to any who need it

**Comment by tas50** [comment]
Stepped upgrade for sure. I don't want to force people to choose between the init system they want a working cookbook. The next release will get things working and then I'll slowly add then slowly deprecate.

**Comment by howdoicomputer** [comment]
As a *small* counterpoint, if you're using Chef cookbooks to build Docker container images via Packer then systemd adds a whole bunch of complexity.

**Comment by t2y** [comment]
I updated to use poise-python cookbook. Could you review #275 ?

**Comment by josephholsten** [comment]
with the cookbook migrated to poise-python (via #275), what's remaining?

**Comment by damacus** [comment]
It to actually converge one of the resources is still broken.

I need a few hours this weekend to go through it and fix that.

**Comment by zevin** [comment]
Just wanted to check on this, as Chef 12 goes EOL in ~ 6 weeks, and this cookbook still depends on the python cookbook, which is not chef13 compliant. If there's anything I can do to help to move this along, please let me know.

**Comment by damacus** [comment]
@zevin would you mind dropping into the #sous-chefs on the chef community slack? We should push this forward quickly!

**Comment by tas50** [comment]
Closing this out since this is fixed on master at this point
